In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [2]:
## Load the dataset
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
## Preprocess the data
### Drop irrelevant columns
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
## Encode categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [5]:
## Onehot encode 'Geography
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [6]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [7]:
geo_encoded_df=pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
## Combine one hot encoder columns with the original data
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [9]:
## Save the encoders and sscaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [10]:
## DiVide the dataset into indepent and dependent features
X=data.drop('Exited',axis=1)
y=data['Exited']

## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [12]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [14]:
## Build Our ANN Model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ## HL1 Connected wwith input layer
    Dense(32,activation='relu'), ## HL2
    Dense(1,activation='sigmoid')  ## output layer
]

)

2026-06-14 17:05:59.801240: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2026-06-14 17:05:59.801279: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2026-06-14 17:05:59.801287: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2026-06-14 17:05:59.801453: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-06-14 17:05:59.801607: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [16]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

In [17]:
## compile the model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy',tf.keras.metrics.Precision(name='precision'),
        tf.keras.metrics.Recall(name='recall'),
        tf.keras.metrics.AUC(name='auc')])

In [18]:
## Set up the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [19]:
## Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [20]:
### Train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100

2026-06-14 17:06:32.857021: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.
2026-06-14 17:06:32.902558: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:961] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node Adam/AssignAddVariableOp.

250/250 [==============================] - 4s 13ms/step - loss: 0.5838 - accuracy: 0.7713 - precision: 0.4229 - recall: 0.3102 - auc: 0.6796 - val_loss: 1.1360 - val_accuracy: 0.6515 - val_precision: 0.2415 - val_recall: 0.3613 - val_auc: 0.5610
Epoch 2/100
250/250 [==============================] - 3s 11ms/step - loss: 2.7473 - accuracy: 0.7044 - precision: 0.3027 - recall: 0.3364 - auc: 0.6058 - val_loss: 3.3178 - val_accuracy: 0.7800 - val_precision: 0.3946 - val_recall: 0.2239 - val_auc: 0.5893
Epoch 3/100
250/250 [==============================] - 2s 10ms/step - loss: 7.2204 - accuracy: 0.7117 - precision: 0.3179 - recall: 0.3516 - auc: 0.5928 - val_loss: 5.9564 - val_accuracy: 0.7090 - val_precision: 0.3121 - val_recall: 0.3995 - val_auc: 0.6034
Epoch 4/100
250/250 [==============================] - 3s 11ms/step - loss: 16.2029 - accuracy: 0.7132 - precision: 0.3176 - recall: 0.3443 - auc: 0.5859 - val_loss: 10.2018 - val_accuracy: 0.7845 - val_precision: 0.3750 - val_recall: 0.1450 - val_auc: 0.5575
Epoch 5/100
250/250 [==============================] - 2s 10ms/step - loss: 13.4761 - accuracy: 0.7279 - precision: 0.3437 - recall: 0.3564 - auc: 0.6011 - val_loss: 39.4861 - val_accuracy: 0.6200 - val_precision: 0.1741 - val_recall: 0.2494 - val_auc: 0.4757
Epoch 6/100
250/250 [==============================] - 3s 10ms/step - loss: 20.8414 - accuracy: 0.7291 - precision: 0.3477 - recall: 0.3631 - auc: 0.5952 - val_loss: 46.7504 - val_accuracy: 0.5590 - val_precision: 0.2298 - val_recall: 0.5293 - val_auc: 0.5512
Epoch 7/100
250/250 [==============================] - 3s 10ms/step - loss: 31.8487 - accuracy: 0.7168 - precision: 0.3209 - recall: 0.3388 - auc: 0.5782 - val_loss: 43.9211 - val_accuracy: 0.7095 - val_precision: 0.2948 - val_recall: 0.3435 - val_auc: 0.5698
Epoch 8/100
250/250 [==============================] - 2s 10ms/step - loss: 35.5037 - accuracy: 0.7210 - precision: 0.3271 - recall: 0.3382 - auc: 0.5824 - val_loss: 30.4919 - val_accuracy: 0.8075 - val_precision: 0.5308 - val_recall: 0.1756 - val_auc: 0.5692
Epoch 9/100
250/250 [==============================] - 3s 11ms/step - loss: 29.6005 - accuracy: 0.7325 - precision: 0.3515 - recall: 0.3571 - auc: 0.5944 - val_loss: 79.4362 - val_accuracy: 0.6930 - val_precision: 0.2582 - val_recall: 0.3003 - val_auc: 0.5439
Epoch 10/100
250/250 [==============================] - 2s 10ms/step - loss: 53.1292 - accuracy: 0.7220 - precision: 0.3292 - recall: 0.3400 - auc: 0.5821 - val_loss: 60.5654 - val_accuracy: 0.7255 - val_precision: 0.2926 - val_recall: 0.2799 - val_auc: 0.5589
Epoch 11/100
250/250 [==============================] - 2s 9ms/step - loss: 52.8673 - accuracy: 0.7181 - precision: 0.3217 - recall: 0.3352 - auc: 0.5783 - val_loss: 67.8293 - val_accuracy: 0.7705 - val_precision: 0.3443 - val_recall: 0.1858 - val_auc: 0.5475

In [21]:
model.save('model.keras')

In [25]:
## Load Tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [26]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6013 (pid 68185), started 0:00:06 ago. (Use '!kill 68185' to kill it.)

In [24]:
results = model.evaluate(X_test, y_test, verbose=0)

# Print metric names with their values
for metric_name, metric_value in zip(model.metrics_names, results):
    print(f"{metric_name}: {metric_value:.4f}")

loss: 1.1360
accuracy: 0.6515
precision: 0.2415
recall: 0.3613
auc: 0.5610